// Code generated by "stringer -type=AttributeType"; DO NOT EDIT.

package swlib

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AttrUnspec-0]
	_ = x[AttrType-1]
	_ = x[AttrID-2]
	_ = x[AttrDevName-3]
	_ = x[AttrAlias-4]
	_ = x[AttrName-5]
	_ = x[AttrVLANs-6]
	_ = x[AttrPorts-7]
	_ = x[AttrPortMap-8]
	_ = x[AttrCPUPort-9]
	_ = x[AttrOPID-10]
	_ = x[AttrOPType-11]
	_ = x[AttrOPName-12]
	_ = x[AttrOPPort-13]
	_ = x[AttrOPVLAN-14]
	_ = x[AttrOPValueInt-15]
	_ = x[AttrOPValueStr-16]
	_ = x[AttrOPValuePorts-17]
	_ = x[AttrOPValueLink-18]
	_ = x[AttrOPDescription-19]
	_ = x[AttrPort-20]
	_ = x[AttrPortMapPorts-0]
	_ = x[AttrPortMapSegment-1]
	_ = x[AttrPortMapVirt-2]
	_ = x[AttrPortMapMax-3]
}

const _AttributeType_name = "AttrUnspecAttrTypeAttrIDAttrDevNameAttrAliasAttrNameAttrVLANsAttrPortsAttrPortMapAttrCPUPortAttrOPIDAttrOPTypeAttrOPNameAttrOPPortAttrOPVLANAttrOPValueIntAttrOPValueStrAttrOPValuePortsAttrOPValueLinkAttrOPDescriptionAttrPort"

var _AttributeType_index = [...]uint8{0, 10, 18, 24, 35, 44, 52, 61, 70, 81, 92, 100, 110, 120, 130, 140, 154, 168, 184, 199, 216, 224}

func (i AttributeType) String() string {
	if i < 0 || i >= AttributeType(len(_AttributeType_index)-1) {
		return "AttributeType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AttributeType_name[_AttributeType_index[i]:_AttributeType_index[i+1]]
}
