// Code generated by "stringer -type=Group"; DO NOT EDIT.

package swlib

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[GroupGlobal-0]
	_ = x[GroupVLAN-1]
	_ = x[GroupPort-2]
}

const _Group_name = "GroupGlobalGroupVLANGroupPort"

var _Group_index = [...]uint8{0, 11, 20, 29}

func (i Group) String() string {
	if i < 0 || i >= Group(len(_Group_index)-1) {
		return "Group(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Group_name[_Group_index[i]:_Group_index[i+1]]
}
